Add function check_if_game_finished.
Ipceeh/minesweeper-beetroot pull request #3
Opened 2023-01-06 13:29 UTC by boryskova

Add a file with the function check_if_game_finished.

2023-01-07 08:56 UTC, Ipceeh requested changes

2023-01-07 08:56 UTC, Ipceeh commented on src/check_if_game_finished.py
> +
No need in `empty_hole_char`

2023-01-07 08:56 UTC, Ipceeh commented on src/check_if_game_finished.py
> +            open_safe_cells += row.count(empty_hole_char)
Wrong data type for matrix

2023-01-07 08:56 UTC, Ipceeh commented on src/check_if_game_finished.py
> +        if open_safe_cells == (len(matrix) ** 2 - len(bombs)):
len(matrix) * len(matrix[0])

2023-01-14 11:26 UTC, Ipceeh approved these changes
Looks good for me!

2023-01-14 11:28 UTC, oksanastep approved these changes

2023-01-14 11:36 UTC, merged